version: '3.8'

services:
  flask_mysql_db:
    image: mysql:5.7
    container_name: flask_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
    volumes:
      - app_mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  flask_crud_app:
    build: .
    container_name: flask_crud_app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://root:root_password@flask_mysql_db/flask_db
    depends_on:
      - flask_mysql_db
    networks:
      - app_network
    ports:
      - "5000:5000"

volumes:
  app_mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
