version: '3.8'

services:
  flask_mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: students_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-import dello schema iniziale
    networks:
      - flask_network

  flask_crud_app:
    build:
      context: .      # Usa la root del progetto!
    restart: always
    depends_on:
      - flask_mysql_db
    environment:
      DB_HOST: flask_mysql_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: students_db
    ports:
      - "5000:5000"
    networks:
      - flask_network
    command: ["python", "app.py"]  # Niente entrypoint.sh, è diretto!

volumes:
  mysql_data:

networks:
  flask_network:
